-- Run this in the Supabase SQL Editor after schema.sql.
-- The quoted name keeps the table visible as "Client" in the Supabase dashboard.

begin;

create table if not exists public."Client" (
  id bigint generated by default as identity primary key,
  email text not null unique,
  subscribed_at timestamptz not null default now(),
  constraint client_email_length_check check (char_length(email) between 3 and 254)
);

alter table public."Client" enable row level security;

-- Subscribers are managed only through the backend's secret key.
revoke all on public."Client" from anon, authenticated;
revoke all on sequence public."Client_id_seq" from anon, authenticated;
grant select, insert on public."Client" to service_role;
grant usage, select on sequence public."Client_id_seq" to service_role;

commit;

notify pgrst, 'reload schema';
